[build-system]
requires = ["setuptools>=67", "wheel", "packaging>=24.2"]
build-backend = "build_backend"
backend-path = ["."]

[project]
name = "cellarc"
version = "0.1.0"
description = "Generation and manipulation of cellular automata datasets"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "matplotlib",
    "jax",
    "flax",
    "cax",
    "tqdm",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "flake8",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["cellarc*"]
exclude = ["tests*", "scripts*"]
